
echo GITHUB_JENKINS_TOKEN=%GITHUB_JENKINS_TOKEN% > .\.env

echo SONAR_DB=%SONAR_DB% >> .\.env
echo SONAR_DB_USER=%SONAR_DB_USER% >> .\.env
echo SONAR_DB_PASSWORD=%SONAR_DB_PASSWORD% >> .\.env
echo SONAR_JDBC_URL=%SONAR_JDBC_URL% >> .\.env

echo JFROG_DB=%JFROG_DB% >> .\.env
echo JFROG_DB_USER=%JFROG_DB_USER% >> .\.env
echo JFROG_DB_PASSWORD=%JFROG_DB_PASSWORD% >> .\.env
echo JF_SHARED_DATABASE_TYPE=%JF_SHARED_DATABASE_TYPE% >> .\.env
echo JF_SHARED_DATABASE_DRIVER=%JF_SHARED_DATABASE_DRIVER% >> .\.env
echo JF_SHARED_DATABASE_URL=%JF_SHARED_DATABASE_URL% >> .\.env
