echo GITHUB_USERNAME=%GITHUB_JENKINS_TOKEN% > .\docker\.env
echo GITHUB_EMAIL=%GITHUB_JENKINS_TOKEN% > .\docker\.env
echo GITHUB_JENKINS_TOKEN=%GITHUB_JENKINS_TOKEN% > .\docker\.env
echo GITHUB_PACKAGE_TOKEN=%GITHUB_JENKINS_TOKEN% > .\docker\.env
echo GITHUB_ARTIFACTORY_URL=%GITHUB_ARTIFACTORY_URL% > .\docker\.env

echo SONAR_DB=%SONAR_DB% >> .\docker\.env
echo SONAR_DB_USER=%SONAR_DB_USER% >> .\docker\.env
echo SONAR_DB_PASSWORD=%SONAR_DB_PASSWORD% >> .\docker\.env
echo SONAR_JDBC_URL=%SONAR_JDBC_URL% >> .\docker\.env
echo SONAR_TOKEN=%SONAR_TOKEN% >> .\docker\.env

echo JFROG_DB=%JFROG_DB% >> .\docker\.env
echo JFROG_DB_USER=%JFROG_DB_USER% >> .\docker\.env
echo JFROG_DB_PASSWORD=%JFROG_DB_PASSWORD% >> .\docker\.env
echo JFROG_DB_ENCRYPTED_PASSWORD=%JFROG_DB_ENCRYPTED_PASSWORD% >> .\docker\.env
echo JF_SHARED_DATABASE_TYPE=%JF_SHARED_DATABASE_TYPE% >> .\docker\.env
echo JF_SHARED_DATABASE_DRIVER=%JF_SHARED_DATABASE_DRIVER% >> .\docker\.env
echo JF_SHARED_DATABASE_URL=%JF_SHARED_DATABASE_URL% >> .\docker\.env

echo CONCOURSE_DB=%CONCOURSE_DB% >> .\docker\.env
echo CONCOURSE_DB_USER=%CONCOURSE_DB_USER% >> .\docker\.env
echo CONCOURSE_DB_PASSWORD=%CONCOURSE_DB_PASSWORD% >> .\docker\.env
echo CONCOURSE_JDBC_URL=%CONCOURSE_JDBC_URL% >> .\docker\.env
echo CONCOURSE_EXTERNAL_URL_1=%CONCOURSE_EXTERNAL_URL_1% >> .\docker\.env
echo CONCOURSE_EXTERNAL_URL_2=%CONCOURSE_EXTERNAL_URL_2% >> .\docker\.env
echo CONCOURSE_CLUSTER_NAME=%CONCOURSE_CLUSTER_NAME% >> .\docker\.env
echo CONCOURSE_ADD_LOCAL_USER=%CONCOURSE_ADD_LOCAL_USER% >> .\docker\.env
echo CONCOURSE_ADD_LOCAL_PASSWORD=%CONCOURSE_ADD_LOCAL_PASSWORD% >> .\docker\.env
echo CONCOURSE_MAIN_TEAM_LOCAL_USER=%CONCOURSE_MAIN_TEAM_LOCAL_USER% >> .\docker\.env
echo CONCOURSE_CLIENT_SECRET=%CONCOURSE_CLIENT_SECRET% >> .\docker\.env
echo CONCOURSE_TSA_CLIENT_SECRET=%CONCOURSE_TSA_CLIENT_SECRET% >> .\docker\.env
echo CONCOURSE_TSA_HOST=%CONCOURSE_TSA_HOST% >> .\docker\.env
