echo GITHUB_USERNAME=%GITHUB_USERNAME% > .\docker\.env
echo GITHUB_EMAIL=%GITHUB_EMAIL% >> .\docker\.env
echo GITHUB_JENKINS_TOKEN=%GITHUB_JENKINS_TOKEN% >> .\docker\.env
echo GITHUB_PACKAGE_TOKEN=%GITHUB_PACKAGE_TOKEN% >> .\docker\.env
echo GITHUB_ARTIFACTORY_URL=%GITHUB_ARTIFACTORY_URL% >> .\docker\.env

echo SONAR_DB=%SONAR_DB% >> .\docker\.env
echo SONAR_DB_USER=%SONAR_DB_USER% >> .\docker\.env
echo SONAR_DB_PASSWORD=%SONAR_DB_PASSWORD% >> .\docker\.env
echo SONAR_JDBC_URL=%SONAR_JDBC_URL% >> .\docker\.env

echo JFROG_DB=%JFROG_DB% >> .\docker\.env
echo JFROG_DB_USER=%JFROG_DB_USER% >> .\docker\.env
echo JFROG_DB_PASSWORD=%JFROG_DB_PASSWORD% >> .\docker\.env
echo JF_SHARED_DATABASE_TYPE=%JF_SHARED_DATABASE_TYPE% >> .\docker\.env
echo JF_SHARED_DATABASE_DRIVER=%JF_SHARED_DATABASE_DRIVER% >> .\docker\.env
echo JF_SHARED_DATABASE_URL=%JF_SHARED_DATABASE_URL% >> .\docker\.env

echo CONCOURSE_DB=%CONCOURSE_DB% >> .\docker\.env
echo CONCOURSE_DB_HOST=%CONCOURSE_DB_HOST% >> .\docker\.env
echo CONCOURSE_DB_PORT=%CONCOURSE_DB_PORT% >> .\docker\.env
echo CONCOURSE_DB_USER=%CONCOURSE_DB_USER% >> .\docker\.env
echo CONCOURSE_DB_PASSWORD=%CONCOURSE_DB_PASSWORD% >> .\docker\.env
echo CONCOURSE_EXTERNAL_URL=%CONCOURSE_EXTERNAL_URL% >> .\docker\.env
echo CONCOURSE_CLUSTER_NAME=%CONCOURSE_CLUSTER_NAME% >> .\docker\.env
echo CONCOURSE_ADD_LOCAL_USER=%CONCOURSE_ADD_LOCAL_USER% >> .\docker\.env
echo CONCOURSE_ADD_LOCAL_PASSWORD=%CONCOURSE_ADD_LOCAL_PASSWORD% >> .\docker\.env
echo CONCOURSE_MAIN_TEAM_LOCAL_USER=%CONCOURSE_MAIN_TEAM_LOCAL_USER% >> .\docker\.env
echo CONCOURSE_TSA_HOST=%CONCOURSE_TSA_HOST% >> .\docker\.env
