---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: maven
    tag: 3.8.6-openjdk-18

caches:
  - path: $HOME/.m2/repository

inputs:
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      mvn -f repo/pom.xml validate
      mvn -f repo/pom.xml clean package -DskipTests=true
