groups:
  - name: development
    jobs:
      - development-build-pine-java-core
  - name: uat
    jobs:
      - uat-build-pine-java-core

resources:
  - name: repo-pine-java-core
    type: git
    icon: github
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  - name: development-build-pine-java-core
    plan:
      - get: repo-pine-java-core
        trigger: true
      - task: build
        input_mapping:
          repo: repo-pine-java-core
        output_mapping:
          repo: repo
        privileged: true
        file: repo-pine-java-core/ci/concourse/build.yaml
      - task: test
        input_mapping:
          repo: repo
        file: repo-pine-java-core/ci/concourse/unit-test.yaml
  - name: uat-build-pine-java-core
    plan:
      - get: repo-pine-java-core
        passed: [ development-build-pine-java-core ]
      - task: build
        input_mapping:
          repo: repo-pine-java-core
        privileged: true
        file: repo-pine-java-core/ci/concourse/build.yaml
      - task: test
        file: repo-pine-java-core/ci/concourse/unit-test.yaml
