groups:
  - name: development
    jobs:
      - development-build-pine-java-core
  - name: uat
    jobs:
      - uat-build-pine-java-core

resources:
  - name: repo-pine-java-core
    type: git
    icon: github
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  - name: development-build-pine-java-core
    public: true
    plan:
      - get: repo-pine-java-core
        trigger: true
      - task: build
        input_mapping:
          repo: repo-pine-java-core
        output_mapping:
          repo: artifact
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18
          caches:
            - path: $HOME/.m2/repository
          inputs:
            - name: repo
          outputs:
            - name: repo
          run:
            path: sh
            args:
              - -exc
              - |
                mvn -f repo/pom.xml validate
                mvn -f repo/pom.xml clean package -DskipTests=true
      - task: test
        input_mapping:
          repo: artifact
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -exc
              - |
                mvn -f repo/pom.xml validate
                mvn -f repo/pom.xml test

  - name: uat-build-pine-java-core
    plan:
      - get: repo-pine-java-core
        passed: [ development-build-pine-java-core ]
      - task: build
        input_mapping:
          repo: repo-pine-java-core
        output_mapping:
          repo: artifact
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18
          caches:
            - path: $HOME/.m2/repository
          inputs:
            - name: repo
          outputs:
            - name: repo
          run:
            path: sh
            args:
              - -exc
              - |
                mvn -f repo/pom.xml validate
                mvn -f repo/pom.xml clean package -DskipTests=true
      - task: test
        input_mapping:
          repo: artifact
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -exc
              - |
                mvn -f repo/pom.xml validate
                mvn -f repo/pom.xml test
