groups:
  - name: development
    jobs:
      - build-pine-java-core
      - test-pine-java-core
  - name: uat
    jobs:
      - build-pine-java-core
      - test-pine-java-core

resources:
  - name: repo-pine-java-core
    type: git
    icon: github
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  - name: test-pine-java-core
    plan:
      - get: repo-pine-java-core
        passed: [ build-pine-java-core ]
        trigger: true
      - task: test
        input_mapping:
          repo: repo-pine-java-core
        privileged: true
        file: repo-pine-java-core/ci/concourse/unit-test.yaml
  - name: build-pine-java-core
    plan:
      - get: repo-pine-java-core
        trigger: true
      - task: build
        input_mapping:
          repo: repo-pine-java-core
        privileged: true
        file: repo-pine-java-core/ci/concourse/build.yaml
