version: '3.8'
secrets:
  github_jenkins_token:
    external: true
services:
  pine-jenkins:
    image: jenkins/latest
    container_name: pine-jenkins-test
    hostname: pine-jenkins-test
    build:
      context: jenkins-file
      dockerfile: Dockerfile
      args:
        GITHUB_JENKINS_TOKEN: ${GITHUB_JENKINS_TOKEN}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/docker_compose/jenkins_configuration:/var/jenkins_home
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

