version: '3.8'
services:
  pine-jenkins:
    image: jenkins/latest
    container_name: pine-jenkins-test
    hostname: pine-jenkins-test
    build:
      context: jenkins-file
      dockerfile: Dockerfile
      args:
        GITHUB_JENKINS_TOKEN: ${GITHUB_JENKINS_TOKEN}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/docker_compose/jenkins_configuration:/var/jenkins_home
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
  pine-sonarqube-db:
    image: postgres
    container_name: pine-sonarqube-db
    hostname: pine-sonarqube-db
    restart: always
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5051:5432"
    volumes:
      - ~/docker_compose/sonarqube-postgresql:/var/lib/postgresql
      - ~/docker_compose/sonarqube-postgresql/sonarqube-postgresql_data:/var/lib/postgresql/data
    ulimits:
      nproc: 262144
      nofile:
        soft: 32000
        hard: 40000
  pine-jfrog-db:
    image: postgres
    container_name: pine-jfrog-db
    hostname: pine-jfrog-db
    restart: always
    environment:
      POSTGRES_DB: artifactory
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: password
    ports:
      - "5052:5432"
    volumes:
      - ~/docker_compose/jfrog-postgresql:/var/lib/postgresql
      - ~/docker_compose/jfrog-postgresql/jfrog-postgresql_data:/var/lib/postgresql/data
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
  # wsl -d docker-desktop
  # sysctl -w vm.max_map_count=262144
  # set vm.max_map_count=262144 in /etc/sysctl.conf then execute sysctl -p
  pine-sonarqube:
    image: sonarqube:community
    container_name: pine-sonarqube
    hostname: pine-sonarqube
    privileged: true
    user: root
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://pine-sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
    ports:
      - "9000:9000"
    volumes:
      - ~/docker_compose/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ~/docker_compose/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ~/docker_compose/sonarqube/sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - pine-sonarqube-db
    links:
      - pine-sonarqube-db
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
  pine-jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: pine-jfrog
    hostname: pine-jfrog
    restart: always
    environment:
      JF_SHARED_DATABASE_TYPE: postgresql
      JF_SHARED_DATABASE_DRIVER: "org.postgresql.Driver"
      JF_SHARED_DATABASE_URL: jdbc:postgresql://pine-jfrog-db:5432/artifactory
      JF_SHARED_DATABASE_USERNAME: artifactory
      JF_SHARED_DATABASE_PASSWORD: password
    ports:
      - "8082:8082"
      - "8081:8081"
    depends_on:
      - pine-jfrog-db
    links:
      - pine-jfrog-db
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

