---
resources:
  - name: git
    icon: github
    type: git
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  # This build job will fetch the source code,
  # then execute a 'build' task which is defined separately in the repository.
  - name: maven-package
    plan:
      - task: maven-package
        config:
          platform: linux
          container_limits: { }
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.6.3
          caches:
           - path: $HOME/.m2/repository
          inputs:
           - name: git
          run:
            path: mvn
            args: [ "-f", "git/pom.xml", "-DskipTests=true", "clean", "package" ]
#  - name: unit-test
#    plan:
#      - get: git
#        version: latest # Just process the latest Git commit, not every commit (this is the default setting)
#        trigger: true # Trigger this job whenever Concourse detects a new Resource version (i.e. a new Git commit)
#        passed:
#          - package
#      - task: run-unit-tests
#        file: git/ci/concourse/unit-test.yml
