resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  - name: build
    plan:
      - get: git-repo
        trigger: true
      - task: maven-package
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18

          inputs:
            - name: git-repo

          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn -f git-repo/pom.xml validate
                mvn -f git-repo/pom.xml clean package -DskipTests=true
  - name: test
    plan:
      - get: git-repo
        trigger: true
      - task: maven-test
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18

          inputs:
            - name: build

          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn -f git-repo/pom.xml validate
                mvn -f git-repo/pom.xml clean package