resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/saman-oss/pine-java-core.git
      branch: main

jobs:
  - name: maven-package
    plan:
      - get: git-repo
        trigger: true
      - task: maven-package
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.6-openjdk-18

          inputs:
            - name: git-repo

          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn -f git-repo/pom.xml validate
                mvn -f git-repo/pom.xml clean package -DskipTests=true
#---
#resources:
#  - name: git
#    icon: github
#    type: git
#    source:
#      uri: https://github.com/saman-oss/pine-java-core.git
#      branch: main
#
#jobs:
#  # This build job will fetch the source code,
#  # then execute a 'build' task which is defined separately in the repository.
#  - name: maven-package
#    plan:
#      - get: git # Concourse is stateless and needs to be given an external input to this Job.
#        version: latest # Just process the latest Git commit, not every commit (this is the default setting)
#        trigger: true
#      - task: maven-package
#        file: git/ci/concourse/maven-package.yml
#  - name: unit-test
#    plan:
#      - get: git
#        version: latest # Just process the latest Git commit, not every commit (this is the default setting)
#        trigger: true # Trigger this job whenever Concourse detects a new Resource version (i.e. a new Git commit)
#        passed:
#          - package
#      - task: run-unit-tests
#        file: git/ci/concourse/unit-test.yml
