FROM ubuntu:latest
MAINTAINER samanalishiri@gmail.com

USER root
RUN apt-get update
RUN apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common openjdk-17-jdk git maven
RUN apt-get update

